### PR TITLE
DOC fix text on null hypothesis in quantile example

### PR DESCRIPTION
**Pull request by lorentzenchr**

### CODE REVIEW

**Comment by lorentzenchr** [comment]
@m-maggi Do you want to review this one?

**Comment by m-maggi** [comment]
@lorentzenchr I am new to code reviews on github, do you see my comment? I see that with a „pending“ label.

**Comment by lorentzenchr** [comment]
At the top right, there is a green button "review changes". If you click, you can select "comment", "approve" and "request changes". I usually only use one of the first 2 choices.

**Review by m-maggi — COMMENTED** [review]
@lorentzenchr this was my only comment which I left by mistake pending

**Pull request merged**
